name=EasyIO
version=1.0.0
author=Mirco Spaggiari <EasyProjects85@proton.me>
maintainer=Mirco Spaggiari <EasyProjects85@proton.me>
sentence=A library for PCF8574A (8-bit) and PCF8575 (16-bit) I2C I/O expanders used on a custom PCB that provide input read (State ON 4 to 30V) and relay output.
paragraph=EasyIO simplifies the control of PCF8574A and PCF8575 expanders using active-LOW output logic. It prevents chip damage and short circuits by automatically enforcing input bits LOW during operations, avoiding incorrect pin state conflicts.
category=Signal Input/Output
url=https://github.com/tuo-username/EasyIO
architectures=*
includes=EasyIO.h

ng operations, avoiding incorrect pin state conflicts.